**Gaussian elimination** and **LU Decomposition**

In [1]:
A = [
    [2.0,  1.0,  1.0],
    [4.0, -6.0,  0.0],
    [-2.0, 7.0,  2.0]
]

In [2]:
pivot_row = 0
pivot_col = 0

In [4]:
target_row = 1

factor = A[target_row][pivot_col]/A[pivot_row][pivot_col]
print(f"Factor to eliminate A[{target_row}][{pivot_col}] is: {factor}")


for k in range(len(A[0])): # len(A[0]) gives us the number of columns # k is columns
    A[target_row][k] = A[target_row][k] - (factor * A[pivot_row][k])

# Print the matrix row by row to see the change
print("Matrix A after one elimination step:")
for row in A:
    print(row)

Factor to eliminate A[1][0] is: 2.0
Matrix A after one elimination step:
[2.0, 1.0, 1.0]
[0.0, -8.0, -2.0]
[-2.0, 7.0, 2.0]


Eliminating all the entires below the first pivot

In [5]:
A = [
    [2.0,  1.0,  1.0],
    [4.0, -6.0,  0.0],
    [-2.0, 7.0,  2.0]
]

n = len(A) # total no. of rows = 3

pivot_row = 0
pivot_col = 0

# loop through all rows below the first pivot
# range(1, 3) will make target_row take the values 1, then 2
for target_row in range(pivot_row + 1, n):
    # factor
    factor = A[target_row][pivot_col] / A[pivot_row][pivot_col]
    print(f"Factor for row {target_row} is: {factor}")


    # update target row
    for k in range(len(A[0])):
        A[target_row][k] = A[target_row][k] - (factor * A[pivot_row][k])

print("\nMatrix A after clearing the first column:")
for row in A:
    print(row)

Factor for row 1 is: 2.0
Factor for row 2 is: -1.0

Matrix A after clearing the first column:
[2.0, 1.0, 1.0]
[0.0, -8.0, -2.0]
[0.0, 8.0, 3.0]


Full forward elimination

In [7]:
A = [
    [2.0,  1.0,  1.0],
    [4.0, -6.0,  0.0],
    [-2.0, 7.0,  2.0]
]



n = len(A)

for pivot_row in range(n - 1): # 3 - 1, creating the sequence [0, 1]
    pivot_col = pivot_row


    for target_row in range(pivot_row + 1, n):
        # factor
        factor = A[target_row][pivot_col] / A[pivot_row][pivot_col]

        for k in range(len(A[0])):
            A[target_row][k] = A[target_row][k] - (factor * A[pivot_row][k])

print("Final Upper Triangular Matrix (U):")
for row in A:
    print(row)

Final Upper Triangular Matrix (U):
[2.0, 1.0, 1.0]
[0.0, -8.0, -2.0]
[0.0, 0.0, 1.0]


LU Decomposition, $A = L \times U$

In [14]:
import copy
import numpy as np


A = [
    [2.0,  1.0,  1.0],
    [4.0, -6.0,  0.0],
    [-2.0, 7.0,  2.0]
]



n = len(A)


# Initialize L
L = [[ 1.0 if i == j else 0.0 for j in range(n)] for i in range(n)]

# U
U = copy.deepcopy(A)
for i in range(n - 1): # i is pivot_row
    for j in range(i+1, n): # j is pivot_col
        factor = U[j][i] / U [i][i]
        L[j][i] = factor
        for k in range(n):
            U[j][k] = U [j][k] - (factor * U[i][k])

print("Lower Triangular matrix, L:")
for row in L: print(row)
print("Upper Triangular matrix, U:")
for row in U: print(row)
print("Final Reconstructed matrix, A_reconstructed")
# convert listst to numpy arrays
L_arr, U_arr = np.array(L), np.array(U)
A_reconstructed = L_arr @ U_arr
print(A_reconstructed)

Lower Triangular matrix, L:
[1.0, 0.0, 0.0]
[2.0, 1.0, 0.0]
[-1.0, -1.0, 1.0]
Upper Triangular matrix, U:
[2.0, 1.0, 1.0]
[0.0, -8.0, -2.0]
[0.0, 0.0, 1.0]
Final Reconstructed matrix, A_reconstructed
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]
